# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-02 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSM', '0002_auto_20180202_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='module_name',
            field=models.CharField(default='-1', max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(default='-1', max_length=100),
        ),
    ]
