# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-23 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DSM', '0003_auto_20180202_1523'),
        ('DSM', '0002_auto_20180312_1831'),
    ]

    operations = [
    ]
